spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8900
  servlet:
    context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/