spring:
  application:
    name: hotpot-eureka
server:
  port: 8761
eureka:
  server:
    # 关闭自我保护防止由于eureka的机制导致 client 被错误显示在线 在开发环境使用
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: server1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/