spring:
  application:
    name: portal-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    feign:
      enabled: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8000
server:
  port: 8080
  servlet:
    context-path: /portal
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/