spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: portal-service
          uri: lb://portal-service
          predicates:
            - Path=/portal/**
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
server:
  port: 7000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/